const fs = require('fs').promises;
const os = require('os');
const path = require('path');

const paths = require('./paths');

const DEFAULT_PROFILE_NAME = 'pwnautomator';
const DEFAULT_SERVER_NAME = 'pwnautomator';
const DEFAULT_PWNO_SERVER_NAME = 'pwno';
const DEFAULT_WRAPPER_PATH = path.join('mcps', 'ghidra_tools', 'wrapper.py');

const WRAPPER_ENABLED_TOOLS = [
    'ghidra_call',
    'help',
    'meta',
    'func_list',
    'func_by_name',
    'func_by_addr',
    'mem_hex',
    'mem_dec',
    'mem_str',
    'mem_asm',
    'disassemble_function',
    'decompile_by_name',
    'decompile_by_addr',
    'search_func',
    'search_str',
    'search_bytes',
    'search_xrefs_to',
    'search_xrefs_from',
    'pwn_payload_write',
    'pwn_payload_read',
    'pwn_payload_list',
    'pwn_payload_execute',
    'pwn_session_poll',
    'pwn_session_send',
    'pwn_session_continue',
    'pwn_session_stop',
    'pwn_session_list'
];

const PWNO_ENABLED_TOOLS = [
    'create_debug_session',
    'list_debug_sessions',
    'close_debug_session',
    'set_file',
    'attach',
    'gdb_poll',
    'gdb_interrupt',
    'finish',
    'jump',
    'return_from_function',
    'until',
    'set_breakpoint',
    'get_session_info',
    'run',
    'step_control',
    'get_context',
    'get_memory',
    'execute',
    'run_command',
    'spawn_process',
    'get_process',
    'kill_process',
    'list_processes',
    'execute_python_script',
    'execute_python_code',
    'install_python_packages',
    'list_python_packages',
    'fetch_repo',
    'pwncli',
    'sendinput',
    'checkoutput',
    'checkevents',
    'pwncli_stop',
    'list_pwncli_sessions',
    'get_retdec_status',
    'get_decompiled_code'
];

const enabled = (value, fallback = true) => {
    if (value === undefined) {
        return fallback;
    }
    return !['0', 'false', 'no', 'off'].includes(String(value).trim().toLowerCase());
};

const resolveRepoPath = (value, fallback) => {
    const raw = String(value || '').trim();
    const target = raw || fallback;
    return path.isAbsolute(target) ? path.resolve(target) : path.resolve(paths.repoRoot, target);
};

const sanitizeName = (value, fallback) => {
    const name = String(value || fallback).trim();
    if (!/^[A-Za-z0-9_.-]+$/.test(name)) {
        throw new Error(`Invalid Codex MCP profile/server name: ${name}`);
    }
    return name;
};

const localMcpHost = (host) => {
    const value = String(host || '').trim();
    if (!value || value === '0.0.0.0' || value === '::') {
        return '127.0.0.1';
    }
    return value;
};

const tomlString = (value) => JSON.stringify(String(value ?? ''));
const tomlArray = (values) => `[${values.map(tomlString).join(', ')}]`;
const tomlInlineTable = (payload) => {
    const entries = Object.entries(payload)
        .filter(([, value]) => value !== undefined && value !== null)
        .map(([key, value]) => `${key} = ${tomlString(value)}`);
    return `{ ${entries.join(', ')} }`;
};

const codexHome = () => process.env.CODEX_HOME || path.join(os.homedir(), '.codex');
const getCodexMcpProfileName = () => sanitizeName(process.env.CODEX_MCP_PROFILE, DEFAULT_PROFILE_NAME);
const shouldConfigureCodexMcp = () => enabled(process.env.CODEX_MCP_AUTOCONFIG, true);

const findEndpoint = (mcpServers, key, fallbackHost, fallbackPort) => {
    const server = (mcpServers || []).find((item) => item?.key === key);
    return {
        host: server?.endpoint?.host || fallbackHost,
        port: String(server?.endpoint?.port || fallbackPort)
    };
};

const buildMcpEnv = (state, mcpServers, trace) => {
    const ghidra = findEndpoint(mcpServers, 'ghidra-mcp', '127.0.0.1', 9999);
    const pwntools = findEndpoint(mcpServers, 'pwntools-mcp', '127.0.0.1', 19191);
    return {
        PYTHONDONTWRITEBYTECODE: '1',
        GHIDRA_HOST: ghidra.host,
        GHIDRA_PORT: ghidra.port,
        GHIDRA_MCP_PWN_HOST: pwntools.host,
        GHIDRA_MCP_PWN_PORT: pwntools.port,
        PWN_AUTOMATOR_CHALLENGE_DIR: paths.challengeDir,
        PWN_AUTOMATOR_BINARY_PATH: state.challenge?.mcpWorkspace?.targetBinaryPath || '',
        PWN_AUTOMATOR_TRACE_ENABLED: process.env.PWN_AUTOMATOR_TRACE_ENABLED || 'true',
        PWN_AUTOMATOR_TRACE_FILE: trace?.currentTracePath || '',
        PWN_AUTOMATOR_TRACE_RUN_ID: state.runId || ''
    };
};

const buildProfileToml = ({ state, mcpServers, serverName, pwnoServerName, wrapperPath, trace }) => {
    const disableIdaMcp = enabled(process.env.CODEX_MCP_DISABLE_IDA_MCP, true);
    const env = buildMcpEnv(state, mcpServers, trace);
    const pwno = findEndpoint(mcpServers, 'pwno-mcp', '127.0.0.1', 5500);
    const pwnoUrl = `http://${localMcpHost(pwno.host)}:${pwno.port}/mcp`;
    const sections = ['# Generated by PwnAutomator. Do not edit while the dashboard is running.'];

    if (disableIdaMcp) {
        sections.push([
            '[mcp_servers.ida_mcp]',
            'command = "python3"',
            'args = ["-c", "raise SystemExit(1)"]',
            'enabled = false'
        ].join('\n'));
    }

    sections.push([
        `[mcp_servers.${serverName}]`,
        'command = "python3"',
        `args = ${tomlArray([wrapperPath])}`,
        `cwd = ${tomlString(paths.repoRoot)}`,
        'enabled = true',
        'default_tools_approval_mode = "approve"',
        `enabled_tools = ${tomlArray(WRAPPER_ENABLED_TOOLS)}`,
        `env = ${tomlInlineTable(env)}`
    ].join('\n'));

    sections.push([
        `[mcp_servers.${pwnoServerName}]`,
        `url = ${tomlString(pwnoUrl)}`,
        'enabled = true',
        'default_tools_approval_mode = "approve"',
        `enabled_tools = ${tomlArray(PWNO_ENABLED_TOOLS)}`
    ].join('\n'));

    return `${sections.join('\n\n')}\n`;
};

const ensureCodexMcpProfile = async (state, mcpServers, trace) => {
    const profileName = getCodexMcpProfileName();
    const serverName = sanitizeName(process.env.CODEX_MCP_SERVER_NAME, DEFAULT_SERVER_NAME);
    const pwnoServerName = sanitizeName(process.env.CODEX_PWNO_MCP_SERVER_NAME, DEFAULT_PWNO_SERVER_NAME);
    const wrapperPath = resolveRepoPath(process.env.CODEX_MCP_WRAPPER, DEFAULT_WRAPPER_PATH);
    const profilePath = path.join(codexHome(), `${profileName}.config.toml`);

    if (!shouldConfigureCodexMcp()) {
        return {
            enabled: false,
            profileName,
            serverName,
            pwnoServerName,
            profilePath: null
        };
    }

    await fs.access(wrapperPath);
    await fs.mkdir(path.dirname(profilePath), { recursive: true });
    await fs.writeFile(profilePath, buildProfileToml({
        state,
        mcpServers,
        serverName,
        pwnoServerName,
        wrapperPath,
        trace
    }), 'utf8');

    return {
        enabled: true,
        profileName,
        serverName,
        pwnoServerName,
        profilePath
    };
};

module.exports = {
    ensureCodexMcpProfile,
    getCodexMcpProfileName,
    PWNO_ENABLED_TOOLS,
    WRAPPER_ENABLED_TOOLS,
    shouldConfigureCodexMcp
};
