const fs = require('fs').promises;
const os = require('os');
const path = require('path');

const paths = require('./paths');

const DEFAULT_PROFILE_NAME = 'pwnautomator';
const DEFAULT_SERVER_NAME = 'pwnautomator';
const DEFAULT_WRAPPER_PATH = path.join('mcps', 'ghidra_tools', 'wrapper.py');
const DEFAULT_ENABLED_TOOLS = [
    'ghidra_call',
    'help',
    'meta',
    'func_list',
    'func_by_name',
    'func_by_addr',
    'mem_hex',
    'mem_dec',
    'mem_str',
    'mem_asm',
    'disassemble_function',
    'decompile_by_addr',
    'decompile_by_name',
    'search_func',
    'search_str',
    'search_bytes',
    'search_xrefs_to',
    'search_xrefs_from',
    'debug_open',
    'debug_run',
    'debug_open_current',
    'debug_attach',
    'debug_close',
    'debug_list',
    'debug_status',
    'debug_break_set',
    'debug_break_del',
    'debug_break_list',
    'debug_cont',
    'debug_stepi',
    'debug_nexti',
    'debug_interrupt',
    'debug_stdin_write',
    'debug_regs',
    'debug_mem',
    'debug_bt',
    'debug_events_poll',
    'debug_context',
    'debug_cmd',
    'debug_ropgadget_chall',
    'debug_ropgadget_libc',
    'debug_restart_server',
    'debug_read_stdout',
    'pwn_payload_write',
    'pwn_payload_read',
    'pwn_payload_list',
    'pwn_payload_execute',
    'pwn_session_poll',
    'pwn_session_send',
    'pwn_session_continue',
    'pwn_session_stop',
    'pwn_session_list'
];

const enabled = (value, fallback = true) => {
    if (value === undefined) {
        return fallback;
    }
    return !['0', 'false', 'no', 'off'].includes(String(value).trim().toLowerCase());
};

const resolveRepoPath = (value) => {
    const raw = String(value || '').trim();
    const target = raw || DEFAULT_WRAPPER_PATH;
    return path.isAbsolute(target) ? path.resolve(target) : path.resolve(paths.repoRoot, target);
};

const sanitizeName = (value, fallback) => {
    const name = String(value || fallback).trim();
    if (!/^[A-Za-z0-9_.-]+$/.test(name)) {
        throw new Error(`Invalid Codex MCP profile/server name: ${name}`);
    }
    return name;
};

const tomlString = (value) => JSON.stringify(String(value ?? ''));

const tomlArray = (values) => `[${values.map(tomlString).join(', ')}]`;

const tomlInlineTable = (payload) => {
    const entries = Object.entries(payload)
        .filter(([, value]) => value !== undefined && value !== null)
        .map(([key, value]) => `${key} = ${tomlString(value)}`);
    return `{ ${entries.join(', ')} }`;
};

const codexHome = () => process.env.CODEX_HOME || path.join(os.homedir(), '.codex');

const getCodexMcpProfileName = () => sanitizeName(process.env.CODEX_MCP_PROFILE, DEFAULT_PROFILE_NAME);

const shouldConfigureCodexMcp = () => enabled(process.env.CODEX_MCP_AUTOCONFIG, true);

const buildMcpEnv = (state, mcpServers, trace) => ({
    PYTHONDONTWRITEBYTECODE: '1',
    GHIDRA_HOST: mcpServers[0].endpoint.host,
    GHIDRA_PORT: String(mcpServers[0].endpoint.port),
    GHIDRA_MCP_DEBUG_HOST: mcpServers[1].endpoint.host,
    GHIDRA_MCP_DEBUG_PORT: String(mcpServers[1].endpoint.port),
    GHIDRA_MCP_PWN_HOST: mcpServers[2].endpoint.host,
    GHIDRA_MCP_PWN_PORT: String(mcpServers[2].endpoint.port),
    PWN_AUTOMATOR_CHALLENGE_DIR: paths.challengeDir,
    PWNTOOLS_MCP_CHALLENGE_DIR: paths.challengeDir,
    PWN_AUTOMATOR_BINARY_PATH: state.challenge?.mcpWorkspace?.targetBinaryPath || '',
    PWNTOOLS_MCP_BINARY_PATH: state.challenge?.mcpWorkspace?.targetBinaryPath || '',
    PWN_AUTOMATOR_TRACE_ENABLED: process.env.PWN_AUTOMATOR_TRACE_ENABLED || 'true',
    PWN_AUTOMATOR_TRACE_FILE: trace?.currentTracePath || '',
    PWN_AUTOMATOR_TRACE_RUN_ID: state.runId || ''
});

const buildProfileToml = ({ state, mcpServers, serverName, wrapperPath, trace }) => {
    const disableIdaMcp = enabled(process.env.CODEX_MCP_DISABLE_IDA_MCP, true);
    const sections = [
        '# Generated by PwnAutomator. Do not edit while the dashboard is running.'
    ];

    if (disableIdaMcp) {
        sections.push([
            '[mcp_servers.ida_mcp]',
            'command = "python3"',
            'args = ["-c", "raise SystemExit(1)"]',
            'enabled = false'
        ].join('\n'));
    }

    sections.push([
        `[mcp_servers.${serverName}]`,
        'command = "python3"',
        `args = ${tomlArray([wrapperPath])}`,
        `cwd = ${tomlString(paths.repoRoot)}`,
        'enabled = true',
        'default_tools_approval_mode = "approve"',
        `enabled_tools = ${tomlArray(DEFAULT_ENABLED_TOOLS)}`,
        `env = ${tomlInlineTable(buildMcpEnv(state, mcpServers, trace))}`
    ].join('\n'));

    return `${sections.join('\n\n')}\n`;
};

const ensureCodexMcpProfile = async (state, mcpServers, trace) => {
    const profileName = getCodexMcpProfileName();
    const serverName = sanitizeName(process.env.CODEX_MCP_SERVER_NAME, DEFAULT_SERVER_NAME);
    const wrapperPath = resolveRepoPath(process.env.CODEX_MCP_WRAPPER);
    const profilePath = path.join(codexHome(), `${profileName}.config.toml`);

    if (!shouldConfigureCodexMcp()) {
        return {
            enabled: false,
            profileName,
            serverName,
            wrapperPath,
            profilePath: null
        };
    }

    await fs.access(wrapperPath);
    await fs.mkdir(path.dirname(profilePath), { recursive: true });
    await fs.writeFile(profilePath, buildProfileToml({ state, mcpServers, serverName, wrapperPath, trace }), 'utf8');

    return {
        enabled: true,
        profileName,
        serverName,
        wrapperPath,
        profilePath
    };
};

module.exports = {
    ensureCodexMcpProfile,
    getCodexMcpProfileName,
    shouldConfigureCodexMcp
};
